---
title: "Scratchwork"
format: pdf
editor: visual
---

```{r}
# load in libraries
package_list <- c("tidyverse", "vroom", "stringr", "dplyr", "ggsci", "gridExtra", "cowplot", "ggplot2", "ggmap", "sf")

# load in packages
for (package_name in package_list) {
  if (!requireNamespace(package_name, quietly = TRUE)) {
    install.packages(package_name)
  }
  library(package_name, character.only = TRUE)
}
```

```{r}
df = read.csv("cleaned_df_1.csv")
```

```{r}
register_stadiamaps("909cd753-30f3-4edd-b91a-0582451bd74f", write = TRUE)
```

```{r}
bbox <- c(left = 4, bottom = 47.27, right = 15.5, top = 56)
germany_map <- get_stadiamap(bbox, zoom = 6, maptype = "stamen_toner_lite")
```

```{r}
df_wind<- subset(df, energy_source_level_2 == "Wind")
df_solar<- subset(df, energy_source_level_2 == "Solar")

```

```{r}
ggmap(germany_map) + 
  geom_point(data = df, 
             aes(x = lon, y = lat, 
                 color = electrical_capacity), size = 0.5, alpha = 0.1) +
  facet_wrap(~ after_2017)
```

```{r}
df_avg_capacity <- df %>%
  group_by(federal_state, after_2017) %>%
  summarise(avg_cap = mean(electrical_capacity, na.rm = TRUE))
```

```{r}
average_df <- merge(df, df_avg_capacity, by = c("federal_state"))
```

```{r}
#library(maps)
library(raster)
```

```{r}
#germany_borders <- map_data("world", region = "Germany")
```

```{r}
state_borders <- getData(country = "Germany", level = 1)
```

```{r}
ggmap(germany_map)
```

```{r}
ggmap(germany_map) +
  geom_polygon(data = average_df, 
               aes(x = lon, y = lat, 
                   group = federal_state, 
                   fill = avg_cap))  + 
  geom_polygon(data = state_borders, 
               aes(x = long, y = lat, group = group), 
               fill = NA, color = "black", size = 0.2) + 
  facet_wrap(~after_2017)
  #geom_path(data = germany_borders, aes(x = long, y = lat, group = group), size = 0.2)
```

```{r}
library(rnaturalearth)
library(rnaturalearthhires)
library(maps)
```

```{r}
map_germany <- ne_countries(country = "Germany", returnclass = "sf")
germany_states <- ne_states(country = "Germany", returnclass = "sf")
```

```{r}
germany_state_data <- left_join(germany_states, df_avg_capacity, by = c("name" = "federal_state"))
```

```{r}
offshore_plants <- df %>%
  filter(technology == "Offshore")

offshore_points <- st_as_sf(offshore_plants, coords = c("lon", "lat"), crs = 4326)

avg_offshore <- offshore_points %>%
  summarise(avg_capacity_offshore = mean(electrical_capacity, na.rm = TRUE))
```

```{r}
prep_offshore <- st_set_geometry(avg_offshore, NULL) %>%
  rename(avg_cap = avg_capacity_offshore)
```

```{r}
combined_offshore <- germany_state_data %>%
  bind_rows(prep_offshore)
```



```{r}
avg_capacity_ocean <- mean(prep_offshore$avg_cap, na.rm = TRUE)
```


```{r}
ocean_polygon <- st_sf(
  geometry = st_sfc(
    st_polygon(list(cbind(c(5.5, 14.75, 14.75, 5.5, 5.5), c(52.8711, 52.8711, 55.9193, 55.9193, 52.8711))))
  ),
  avg_cap = avg_capacity_ocean
) %>%
  st_set_crs(4326)
```


```{r}
ggplot() + 
  geom_sf(data = germany_state_data, aes(fill = avg_cap)) + 
  scale_fill_viridis_c() + 
  labs(fill = "Avg. Capacity (MWh)") + theme_minimal() + 
  labs(
    title = "Avg. Capacity of Renewable Energy Plants",
    subtitle = "Data from 2016 to 2018"
  ) + 
  theme(
    text = element_text(size = 8),
      plot.title = element_text(size = 10)
  ) + 
  facet_wrap(~ after_2017)


#geom_sf(data = ocean_polygon, aes(fill = avg_cap), color = NA) +
```



